[window]
dynamic_title = false
padding.x = 10
padding.y = 10

[font]
normal.family = "Noto Sans Mono"
size = 12

[general]
import = [
  "~/.config/alacritty/theme.toml",
  "~/.config/alacritty/cursor.toml",
  "~/.config/alacritty/binds.toml"
]
