[colors.primary]
background = "#12171F"
foreground = "#E6E6E6"

[colors.cursor] 
text = "#0E141B" 
cursor = "#F9B233"

[colors.normal] 
black = "#0E141B" 
red = "#E84C3D" 
green = "#F9B233" 
yellow = "#F7E1B5" 
blue = "#009BCA" 
magenta = "#E84C3D" 
cyan = "#009BCA" 
white = "#E6E6E6"

[colors.bright] 
black = "#333333" 
red = "#FF5F4C" 
green = "#FFCC55" 
yellow = "#FFE7A3" 
blue = "#33B8E6" 
magenta = "#FF6B5C" 
cyan = "#33CFFF" 
white = "#FFFFFF"

